# Generated by Django 4.2.26 on 2025-11-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Comedy', max_length=100),
            preserve_default=False,
        ),
    ]
